### ISSUE TITLE
Syntax Error when running spotifyside.py

### ISSUE THREAD

**Issue by TheStonedSpider** [singak1/YT2Spotify#2]
Keep getting syntax errors and "unknown character" errors when running the spotifyside.py havent ran the ytside.py yet. I've got latest python.

**Comment by singak1** [comment]
> Keep getting syntax errors and "unknown character" errors when running the spotifyside.py havent ran the ytside.py yet. I've got latest python.

Would you be able to share a screenshot of the errors?

**Comment by TheStonedSpider** [comment]
first syntax error shows a dot or something and after deleting both of them on that line then it says >>is invalid syntax at beginning of file.
![syntaxerror1](https://user-images.githubusercontent.com/119985502/206069382-9df121fa-4136-4a3f-8db7-25698503d538.png)
![syntaxerror2](https://user-images.githubusercontent.com/119985502/206069389-b1e1aa8a-922a-4efb-9284-eb6d49201449.png)

**Comment by TheStonedSpider** [comment]
Traceback (most recent call last):
  File "C:\YT2Spotify-main\spotifySide.py", line 1, in <module>
    import spotipy
  File "C:\YT2Spotify-main\spotipy\__init__.py", line 1, in <module>
    from .cache_handler import *  # noqa
  File "C:\YT2Spotify-main\spotipy\cache_handler.py", line 15, in <module>
    from redis import RedisError
ModuleNotFoundError: No module named 'redis'
